// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ClientSuite.iOS
{
	public partial class SettingViewController : UITableViewController
	{
		public SettingViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
